### PR TITLE
Reanimate Hands-On Training Repository

### PR DESCRIPTION
**Pull request by ksuess**
Upgrade to Volto 7.4

### CODE REVIEW

**Comment by ksuess** [comment]
please help onboarding and review, @plone/volto-team

**Comment by ksuess** [comment]
It seems to be necessary to mention babel in dependencies (package.json) to get paths right.
```
  "dependencies": {
    ...
    "@babel/core": "7.9.6",
    ...
```
If not:
```
Module build failed (from ./node_modules/razzle/node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/plugin-proposal-function-bind'
```

**Comment by tisto** [comment]
@ksuess awesome! Thanks a lot Katja!!!

**Comment by ksuess** [comment]
Well, thank you for approving, @tisto. For a merge of the same diff on on all training chapters: https://github.com/collective/volto-hands-on-training/issues/6

**Pull request merged**
